### Get all Convocatories
GET http://localhost:3001/api/admin/convocatories

### New Convocatory
POST http://localhost:3001/api/admin/new-conv
Content-Type: application/json

{
    "name": "allValues.nameConvocatory",
    "maxQuotas": 10,
    "initialDate": "allValues.startDate",
    "finalDate": "allValues.endDate",
    "initialBootcampDate": "allValues.startDateBootcamp",
    "finalBootcampDate": "allValues.endDateBootcamp",
    "residenceCountry": ["Array"],
    "residencyDepartment": ["Array"],
    "maxAge": "21",
    "maxSocioeconomicStratus": 2,
    "gender":["Array"],
    "typePopulation":["Array"]
}