### Get all Convocatories
GET http://165.227.220.15/api/admin/convocatories

### Get one Convocatory
GET http://localhost:3001/api/admin/convocatory/6231dea2f8bb6b79f57c25e8

### Delete one convocatory
DELETE http://localhost:3001/api/admin/convocatory/:id

### New Convocatory
POST http://localhost:3001/api/admin/new-conv
Content-Type: application/json

{
    "name": "allValues.nameConvocatory",
    "maxQuotas": 10,
    "initialDate": "allValues.startDate",
    "finalDate": "allValues.endDate",
    "initialBootcampDate": "allValues.startDateBootcamp",
    "finalBootcampDate": "allValues.endDateBootcamp",
    "residenceCountry": ["Array"],
    "residencyDepartment": ["Array"],
    "maxAge": "21",
    "maxSocioeconomicStratus": [2],
    "gender":["Array"],
    "typePopulation":["Array"]
}

### Update Convocatory
PUT  https://selectprocess.herokuapp.com/api/admin/update-conv/6231dd4ff8bb6b79f57c259d
Content-Type: application/json

{
    "name": "Conv Update from backend",
    "maxQuotas": 10,
    "initialDate": "allValues.startDate",
    "finalDate": "allValues.endDate",
    "initialBootcampDate": "allValues.startDateBootcamp",
    "finalBootcampDate": "allValues.endDateBootcamp",
    "residenceCountry": ["Array"],
    "residencyDepartment": ["Array"],
    "maxAge": "21",
    "maxSocioeconomicStratus": 2,
    "gender":["Array"],
    "typePopulation":["Array"]
}

### Register candidate
PATCH http://localhost:3001/api/admin/update-candidate/:idConvocatoria
Content-Type: application/json

{
    "usersRegistered" : ["idUsuario", "Otrousuario"]
}