### Create user profile when a user press the create acount button
POST http://localhost:3001/api/user/register
Content-Type: application/json

{
  "names": "user_names",
  "surname": "user_surname@asdads.com",
  "email": "hola@hola.com",
  "password": "12345678"
}

### Login user
POST http://localhost:3001/api/user/login
Content-Type: application/json

{
    "email":"lizette.sevillano.c@gmail.com",
    "password": "1234567"
}

### Token activation when a user create an acount and activate it fron the email registered 
GET http://localhost:3001/api/user/activation/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lcyI6InVzZXJfbmFtZXMiLCJzdXJuYW1lIjoidXNlcl9zdXJuYW1lQGFzZGFkcy5jb20iLCJlbWFpbCI6ImhvbGFAaG9sYS5jb20iLCJwYXNzd29yZEhhc2giOiIkMmIkMTIkYi91MzE0S3YyQy5iQ2pRN1NVS2JuLnB1RE82YmRrSWZhUWhTTC9kcDJOeUVkTDROOEllaHEiLCJpYXQiOjE2NDc4ODY4NTUsImV4cCI6MTY0Nzg4NzE1NX0.OMT66aC0JmqtheGM7JRurhj0YyHSi2LyO5rnfQnDy54
### activation_token is a token gerenated when a user profile create a count.  

### Get all users info with admin auth
### An unexpired authentication token is needed here set token in header 
GET http://localhost:3001/api/user/all_info
Content-Type: application/json


### 
GET http://localhost:3001/api/user/info
Content-Type: application/json

{
  "user": {
    "id": "6237c2f0377003c146ab9df3"
  }
}

### Reset password when a user press the forgot my password button
POST http://localhost:3001/api/user/forgot
Content-Type: application/json

{
  "email":"user_email",
}

### Update users role
### An unexpired authentication token is needed here set token in header 
PATCH http://localhost:3001/api/user/update_role/6237c2f0377003c146ab9df3
Content-Type: application/json

{
  "role": 1
}

###
POST http://localhost:3001/api/candidate/profile
Content-Type: application/json

{
  "firstName": "ja",
  "secondName": "iro",
  "firstSurname": "Sol",
  "secondSurname": "arte",
  "documentType": "CC",
  "documentNumber": 123411234
}